modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="bimbysmod"
version="1.0.0"
displayName="Bimbys mod "
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Nathan15141, MCreator"

[[dependencies.bimbysmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



